import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xff6c5e00),
  onPrimary: Color(0xffffffff),
  primaryContainer: Color(0xffffe32b),
  onPrimaryContainer: Color(0xff211c00),
  secondary: Color(0xff655f41),
  onSecondary: Color(0xffffffff),
  secondaryContainer: Color(0xffece3bc),
  onSecondaryContainer: Color(0xff201c05),
  tertiary: Color(0xff426650),
  onTertiary: Color(0xffffffff),
  tertiaryContainer: Color(0xffc3ecd0),
  onTertiaryContainer: Color(0xff002111),
  error: Color(0xffba1a1a),
  errorContainer: Color(0xffffdad6),
  onError: Color(0xffffffff),
  onErrorContainer: Color(0xff410002),
  background: Color(0xfffffbff),
  onBackground: Color(0xff1d1c16),
  surface: Color(0xfffffbff),
  onSurface: Color(0xff1d1c16),
  surfaceVariant: Color(0xffe9e2d0),
  onSurfaceVariant: Color(0xff4a4739),
  outline: Color(0xff7b7768),
  onInverseSurface: Color(0xfff5f0e7),
  inverseSurface: Color(0xff32302a),
  inversePrimary: Color(0xffe1c700),
  shadow: Color(0xff000000),
  surfaceTint: Color(0xff6c5e00),
  outlineVariant: Color(0xffccc6b5),
  scrim: Color(0xff000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xff6c5e00),
  onPrimary: Color(0xffffffff),
  primaryContainer: Color(0xffffe32b),
  onPrimaryContainer: Color(0xff211c00),
  secondary: Color(0xff655f41),
  onSecondary: Color(0xffffffff),
  secondaryContainer: Color(0xffece3bc),
  onSecondaryContainer: Color(0xff201c05),
  tertiary: Color(0xff426650),
  onTertiary: Color(0xffffffff),
  tertiaryContainer: Color(0xffc3ecd0),
  onTertiaryContainer: Color(0xff002111),
  error: Color(0xffba1a1a),
  errorContainer: Color(0xffffdad6),
  onError: Color(0xffffffff),
  onErrorContainer: Color(0xff410002),
  background: Color(0xfffffbff),
  onBackground: Color(0xff1d1c16),
  surface: Color(0xfffffbff),
  onSurface: Color(0xff1d1c16),
  surfaceVariant: Color(0xffe9e2d0),
  onSurfaceVariant: Color(0xff4a4739),
  outline: Color(0xff7b7768),
  onInverseSurface: Color(0xfff5f0e7),
  inverseSurface: Color(0xff32302a),
  inversePrimary: Color(0xffe1c700),
  shadow: Color(0xff000000),
  surfaceTint: Color(0xff6c5e00),
  outlineVariant: Color(0xffccc6b5),
  scrim: Color(0xff000000),
);
const textTheme = TextTheme(
  bodyLarge: TextStyle(
    fontFamily: 'Roboto',
    fontSize: 32,
    fontWeight: FontWeight.w500,
  ),
  bodyMedium: TextStyle(
    fontFamily: 'Roboto',
    fontSize: 16,
    fontWeight: FontWeight.w400,
  ),
  bodySmall: TextStyle(
    fontFamily: 'Roboto',
    fontSize: 14,
    fontWeight: FontWeight.w400,
  ),
  headlineLarge: TextStyle(),
  headlineMedium: TextStyle(),
  headlineSmall: TextStyle(),
  labelLarge: TextStyle(
    fontFamily: 'Roboto',
    fontSize: 14,
    fontWeight: FontWeight.w500,
  ),
  labelMedium: TextStyle(),
  labelSmall: TextStyle(),
  titleLarge: TextStyle(),
  titleMedium: TextStyle(
    fontFamily: 'Roboto',
    fontSize: 20,
    fontWeight: FontWeight.w500,
  ),
  titleSmall: TextStyle(),
  displayLarge: TextStyle(),
  displayMedium: TextStyle(),
  displaySmall: TextStyle(),
);
