name: todo_list
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  very_good_analysis: ^5.0.0+1
  get: ^4.6.5
  freezed_annotation: ^2.2.0
  uuid: ^3.0.7
  freezed: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5 

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto 
      fonts:
        - asset: assets/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/Roboto/Roboto-Regular.ttf
          weight: 400
